---
title: "Distributions Assignment"
author: "Björn Eyríkur Helgason"
date: "27. apr. 2016"
output: pdf_document
---
We first define a function that returns a list of $n$ random observations from a normal distribution with mean $m$ and SD $sd$. I assume $n$, $m$ and $sd$ to be defined outside the function, as it would otherwise just be a wrapper for rnorm.

```{r}
n <- 1
m <- 0
SD <- 1

distribution.change <- function(){
  wList <- rnorm(n,mean = m,sd = SD)
  return(wList)
}
```
We now procede to generate 10 data sets with $n=10000$, $m=100$ and $sd$ varying from 1 to 10, whilst plotting the empirical CDF.

```{r}
n <- 10000
m <- 100
plot(0,0, type="n", xlab = "x", ylab = "F(x)", xlim = c(0,200), ylim = c(0,1), main = "Empirical CDF")
for(i in 1:10){
  SD <- i
  workList <- distribution.change()
  lines(ecdf(workList), col = rgb(i/10,0,1 - i/10))
}

```

We repeat for the pdf

```{r}
n <- 10000
m <- 100
plot(0,0, type="n", xlab = "x", ylab = "f(x)", xlim = c(50,150), ylim = c(0,0.5), main = "PDF")
for(i in 1:10){
  SD <- i
  workList <- distribution.change()
  lines(density(workList), col = rgb(i/10,0,1 - i/10))
}

```
